site_name: AutoCRAT & Supplementary Scripts Documentationtheme:  name: material  # Use Material theme (optional)
  features:
    - toc.hidden  # Hides the Table of Contents from the right sidebarnav:  - Home: index.md
  - Scripts:
    - MergeAutoCRAT: MergeAutoCRAT.md
    - ScreenRNSA: ScreenRNSA.md
    - ScreenByRepTime: ScreenByRepTime.md
    - CherryPicker: CherryPicker.md
    - RNSAheatmap: RNSAheatmap.md
    - RNSAsubpop: RNSAsubpop.md
    - PlotRNSA: PlotRNSA.md
    - RNSAsigmoid: RNSAsigmoid.md
    - SwarmPlot: SwarmPlot.md

extra_css:
  - assets/extra.css
  - assets/custom.css

extra_javascript:
  - assets/custom.js

extra:
  analytics:
    provider: google
    property: G-VHGBMP72WJ  # Replace with your Measurement ID


site_url: https://amir-aharoni-lab.github.io/AutoCRAT-pipeline-doc/


