site_name: AutoCRAT & Supplementary Scripts Documentation
theme:
  name: material  # Use Material theme (optional)
  features:
    - toc.hidden  # Hides the Table of Contents from the right sidebar
nav:
  - Overview: index.md
  - Installation: installation.md
  - Quick Start: quick_start.md
  - Configuration: configuration.md
  - Pipeline Workflow: 
    - Workflow Overview: pipeline.md 
    - "Dot Detection & Tracking": step2_detection_and_tracking.md
    - Replication Analysis: step3_replication_analysis.md
    - Replisome-Normalized Signal Averaging: step4_rnsa.md
    - Double-Strand Break Detection: step5_dsb.md
  - Output Files: output_files.md
  - Supplementary Scripts:
    - MergeAutoCRAT: MergeAutoCRAT.md
    - ScreenRNSA:
      - ScreenRNSA: ScreenRNSA.md
      - ScreenRNSA_Cutoff: ScreenRNSA_Cutoff.md
    - ScreenCells_TP_Intensity: ScreenCells_TP_Intensity.md
    - ScreenCells_TP_Intensity_colocalize: ScreenCells_TP_Intensity_colocalize.md
    - ScreenByRepTime: ScreenByRepTime.md
    - CherryPicker: CherryPicker.md
    - RNSAheatmap: RNSAheatmap.md
    - RNSAsubpop: RNSAsubpop.md
    - PlotRNSA: PlotRNSA.md
    - RNSAsigmoid: RNSAsigmoid.md
    - SwarmPlot: SwarmPlot.md
  - Contact: contact.md

extra_css:
  - assets/extra.css
  - assets/custom.css

extra_javascript:
  - assets/custom.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML


extra:
  analytics:
    provider: google
    property: G-VHGBMP72WJ  # Replace with your Measurement ID



site_url: https://amir-aharoni-lab.github.io/AutoCRAT-pipeline-doc/


